### PR TITLE
Fix Wipes

### PR DESCRIPTION
**Pull request by lkse**
USER_STARS_QUERY was not a docstring, just a collection of strings.
this should fix wiping.

### CODE REVIEW

**Comment by iotazz** [comment]
:skull:

**Comment by lkse** [comment]
In Theory, Aochi's way of setting up wipes, outlined in https://github.com/kawatapw/RealistikPanel/commit/a400003f8d579989aa9cb6d87c403eb4dd58aa4c, _should_ work, as it prints the following.
<details>
<summary> Aochi's Print</summary>
<pre>
UPDATE users_stats SET ranked_score_std = 0, playcount_std = 0, total_score_std = 0, replays_watched_std = 0, ranked_score_taiko = 0, playcount_taiko = 0, total_score_taiko = 0, replays_watched_taiko = 0, ranked_score_ctb = 0, playcount_ctb = 0, total_score_ctb = 0, replays_watched_ctb = 0, ranked_score_mania = 0, playcount_mania = 0, total_score_mania = 0, replays_watched_mania = 0, total_hits_std = 0, total_hits_taiko = 0, total_hits_ctb = 0, total_hits_mania = 0, level_std = 0, level_taiko = 0, level_ctb = 0, level_mania = 0, playtime_std = 0, playtime_taiko = 0, playtime_ctb = 0, playtime_mania = 0, avg_accuracy_std = 0.000000000000, avg_accuracy_taiko = 0.000000000000, avg_accuracy_ctb = 0.000000000000, avg_accuracy_mania = 0.000000000000, pp_std = 0, pp_taiko = 0, pp_ctb = 0, pp_mania = 0 WHERE id = 1
</pre>
</details>

This is all fine and dandy, but when thrown through mySQL, it throws a syntax error.

So, I took the old multiline string and implemented it into aochi's solution.
Creating This:

<details>
<summary>"New" Version of aochi's solution</summary>
<pre>
USER_STATS_QUERY = ("""UPDATE
        users_stats
    SET
        ranked_score_std = 0,
        playcount_std = 0,
        total_score_std = 0,
        replays_watched_std = 0,
        ranked_score_taiko = 0,
        playcount_taiko = 0,
        total_score_taiko = 0,
        replays_watched_taiko = 0,
        ranked_score_ctb = 0,
        playcount_ctb = 0,
        total_score_ctb = 0,
        replays_watched_ctb = 0,
        ranked_score_mania = 0,
        playcount_mania = 0,
        total_score_mania = 0,
        replays_watched_mania = 0,
        total_hits_std = 0,
        total_hits_taiko = 0,
        total_hits_ctb = 0,
        total_hits_mania = 0,
        level_std = 0,
        level_taiko = 0,
        level_ctb = 0,
        level_mania = 0,
        playtime_std = 0,
        playtime_taiko = 0,
        playtime_ctb = 0,
        playtime_mania = 0,
        avg_accuracy_std = 0.000000000000,
        avg_accuracy_taiko = 0.000000000000,
        avg_accuracy_ctb = 0.000000000000,
        avg_accuracy_mania = 0.000000000000,
        pp_std = 0,
        pp_taiko = 0,
        pp_ctb = 0,
        pp_mania = 0
    WHERE
        id = %s
    """)
</pre>
</details>
    
   My new solution includes the 'WHERE' Statement because of another syntax error when parsing the string at Lines 1197 & 1218 in commit https://github.com/kawatapw/RealistikPanel/commit/32a5d4d687335ce752c6c5e9ac82d7d2ec11950a. those lines should pass the proper information; as outlined by their removal in the same commit (https://github.com/kawatapw/RealistikPanel/commit/32a5d4d687335ce752c6c5e9ac82d7d2ec11950a), while no longer passing santax errors.

**Comment by 7ez** [comment]
> USER_STARS_QUERY was not a docstring, just a collection of strings. this should fix wiping.

ok mate

**Comment by 7ez** [comment]
if its a collection of strings then why does wiping on vn work?

**Comment by 7ez** [comment]
🥱🥱🥱

**Comment by 7ez** [comment]
right, unrelated pr

**Pull request closed without merging**
